### ISSUE TITLE
Should this line have ", ".join( )?

### ISSUE THREAD

**Issue by daqieq** [slott56/Stingray-Reader#1]
https://github.com/slott56/Stingray-Reader/blob/4ac963276812c77075faae43102e1342f533fb5e/stingray/cobol/defs.py#L988

Please excuse my ignorance ... I've done a fair amount of searching to resolve this error, but I'm also new-ish to Python.

The above line in the cobol/defs.py is returning the following error:

`TypeError: unsupported format string passed to map.__format__`

When I use a copybook that has the following ODO:

```
          02 GROUP-LABL.
             03 LABL-STDY-GP-AR-CT           PIC 9(00004).
			 03 LABL-STDY-GP-AR
                OCCURS 0 TO 40 TIMES DEPENDING ON LABL-STDY-GP-AR-CT.
                05 LABL-PRSN-ID              PIC 9(00009).
                05 LABL-GNPR-ID              PIC 9(00009).
                05 LABL-GNRC-ID              PIC 9(00009).
                05 LABL-GNRC-AT              PIC -9(00012).9(6).
                05 LABL-GNRC-QY              PIC -9(00015).
                05 LABL-GNRC-CD              PIC X(00006).
                05 LABL-GNRC-PT              PIC -9(00003).9(4).
                05 LABL-GNRC-TX              PIC X(00030).
                05 LABL-QRY-FILL-50-TX       PIC X(00050).
```

When I remove the ODO portion from the group the error goes away, but obviously the ODO functionality is lost.

My analysis found that "{:s}".format() doesn't accept a map() object, so I converted it to a string first using ", ".join().

This is my code snippet that I'm using in a Jupyter notebook:

```
import pandas as pd
import numpy as np
from ayx import Alteryx
from pprint import PrettyPrinter
from stingray.cobol.loader import COBOLSchemaLoader

with open(r"C:\Temp\cobol_copybook\qbe44x10.cbl", "r") as copy_book:
    schema = COBOLSchemaLoader(copy_book).load()
```

I tried uninstalling stingray from my venv, making the suggested change to the Stingray-Reader-master\stingray\cobol\defs.py file and reinstalling using `python setup.py install`. However, it's still returning the same error message even though the code line inside the __repr__ function has changed to include the ", ".join().

Do I need to build the project again to include this change? It feels like the code is ignoring the updated defs.py file. Is there a compiled version installed somewhere that I missed?

**Comment by slott56** [comment]
Thanks for the concrete example. I'll add it as a unit test case and see what happens.

**Comment by slott56** [comment]
What version of Python are you using? This seems to work with Python 3.5, 3.6, and 3.7.

**Comment by slott56** [comment]
The `map()` needs to be `list(map(...))`.
